name: 'off3nied'

on:
  schedule:
      - cron:  '*/15 * * * *' 
  push:
    branches:    
      - main
jobs:
  push:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          operating-system: ['ubuntu-20.04']
      steps:
      - uses: actions/checkout@v3 
      - name: Run with setup-python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          update-environment: false
          cache: 'pipenv'
      - name: Install pipenv
        run: pip3 install --user pipenv
      - name: Install dependecies
        run:  pipenv --python python3 && pipenv install
      - name: Build
        run: pipenv run build
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git diff
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git config --global credential.helper store
          echo "machine github.com login off3nied password $GITHUB_TOKEN" > ~/.netrc
          git add README.md
          git commit -m "GitHub Action Auto Updated"
          git push
